GP_NAMES_EN_TO_FR = {"British Grand Prix": "Grand Prix de Grande-Bretagne",
                     "Monaco Grand Prix": "Grand Prix de Monaco",
                     "Indianapolis 500": "500 miles d'Indianapolis",
                     "Swiss Grand Prix": "Grand Prix de Suisse",
                     "Belgian Grand Prix": "Grand Prix de Belgique",
                     "French Grand Prix": "Grand Prix de France",
                     "Italian Grand Prix": "Grand Prix d'Italie",
                     "German Grand Prix": "Grand Prix d'Allemagne",
                     "Spanish Grand Prix": "Grand Prix d'Espagne",
                     "Dutch Grand Prix": "Grand Prix des Pays-Bas",
                     "Argentine Grand Prix": "Grand Prix d'Argentine",
                     "Pescara Grand Prix": "Grand Prix de Pescara",
                     "Portuguese Grand Prix": "Grand Prix du Portugal",
                     "Moroccan Grand Prix": "Grand Prix du Maroc",
                     "United States Grand Prix": "Grand Prix des Etats-Unis",
                     "South African Grand Prix": "Grand Prix d'Afrique du Sud",
                     "Mexican Grand Prix": "Grand Prix du Mexique",
                     "Austrian Grand Prix": "Grand Prix d'Autriche",
                     "Canadian Grand Prix":	"Grand Prix du Canada",
                     "Brazilian Grand Prix": "Grand Prix du Brésil",
                     "Swedish Grand Prix":	"Grand Prix de Suède",
                     "United States Grand Prix West": "Grand Prix des Etats-Unis Ouest",
                     "Japanese Grand Prix": "Grand Prix du Japon",
                     "San Marino Grand Prix": "Grand Prix de Saint-Marin",
                     "Caesars Palace Grand Prix": "Grand Prix du Caesars Palace",
                     "Detroit Grand Prix": "Grand Prix de Détroit",
                     "European Grand Prix": "Grand Prix d'Europe",
                     "Dallas Grand Prix": "Grand Prix de Dallas",
                     "Australian Grand Prix": "Grand Prix d'Australie",
                     "Hungarian Grand Prix": "Grand Prix de Hongrie",
                     "Pacific Grand Prix":  "Grand Prix du Pacifique",
                     "Luxembourg Grand Prix": "Grand Prix du Luxembourg",
                     "Malaysian Grand Prix": "Grand Prix de Malaisie",
                     "Bahrain Grand Prix": "Grand Prix de Bahreïn",
                     "Chinese Grand Prix": "Grand Prix de Chine",
                     "Turkish Grand Prix": "Grand Prix de Turquie",
                     "Singapore Grand Prix": "Grand Prix de Singapour",
                     "Abu Dhabi Grand Prix": "Grand Prix d'Abou Dabi",
                     "Korean Grand Prix": "Grand Prix de Corée",
                     "Indian Grand Prix": "Grand Prix d'Inde",
                     "Russian Grand Prix": "Grand Prix de Russie",
                     "Azerbaijan Grand Prix": "Grand Prix d'Azerbaïdjan",
                     "Styrian Grand Prix": "Grand Prix de Styrie",
                     "70th Anniversary Grand Prix": "Grand Prix du 70ème Anniversaire",
                     "Tuscan Grand Prix": "Grand Prix de Toscane",
                     "Eifel Grand Prix": "Grand Prix de l'Eifel",
                     "Emilia Romagna Grand Prix": "Grand Prix d'Emilie-Romagne",
                     "Sakhir Grand Prix": "Grand Prix de Sakhir",
                     "Mexico City Grand Prix": "Grand Prix de Mexico",
                     "São Paulo Grand Prix": "Grand Prix de Sao Paulo",
                     "Qatar Grand Prix": "Grand Prix du Qatar",
                     "Saudi Arabian Grand Prix": "Grand Prix d'Arabie Saoudite",
                     "Miami Grand Prix": "Grand Prix de Miami"}

COUNTRIES_EN_TO_FR = {"UK": "Royaume-Uni",
                      "Monaco": "Monaco",
                      "USA": "Etats-Unis",
                      "Switzerland": "Suisse",
                      "Belgium": "Belgique",
                      "France": "France",
                      "Italy": "Italie",
                      "Germany": "Allemagne",
                      "Spain": "Espagne",
                      "Netherlands": "Pays-Bas",
                      "Argentina": "Argentine",
                      "Portugal": "Portugal",
                      "Morocco": "Maroc",
                      "South Africa": "Afrique du Sud",
                      "Mexico": "Mexique",
                      "Austria": "Autriche",
                      "Canada": "Canada",
                      "Brazil": "Brésil",
                      "Sweden": "Suède",
                      "Japan": "Japon",
                      "Australia": "Australie",
                      "Hungary": "Hongrie",
                      "Malaysia": "Malaisie",
                      "Bahrain": "Bahreïn",
                      "China": "Chine",
                      "Turkey": "Turquie",
                      "Singapore": "Singapour",
                      "UAE": "Emirats Arabes Unis",
                      "Korea": "Corée du Sud",
                      "India": "Inde",
                      "Russia": "Russie",
                      "Azerbaijan": "Azerbaïdjan",
                      "Qatar": "Qatar",
                      "Saudi Arabia": "Arabie Saoudite",
                      "United States": "Etats-Unis",
                      "Great Britain": "Royaume-Uni",
                      "Abu Dhabi": "Emirats Arabes Unis"}

CIRCUIT_LOCATIONS = {"Silverstone": "Circuit de Silverstone",
                     "Monte-Carlo": "Circuit de Monaco",
                     "Indianapolis": "Indianapolis Motor Speedway",
                     "Bern": "Circuit de Bremgarten",
                     "Spa": "Circuit de Spa-Francorchamps",
                     "Reims": "Circuit de Reims-Gueux",
                     "Monza": "Autodromo nazionale di Monza",
                     "Nürburg": "Nürburgring",
                     "Barcelona": "Circuit de Pedralbes",
                     "Rouen": "Circuit de Rouen-les-Essarts",
                     "Zandvoort": "Circuit de Zandvoort",
                     "Buenos Aires": "Autódromo de Buenos Aires",
                     "Liverpool": "Circuit d'Aintree",
                     "Pescara": "Circuit de Pescara",
                     "Oporto": "Circuit de Boavista",
                     "Casablanca": "Circuit d'Ain-Diab",
                     "Berlin": "AVUS",
                     "Lisbon": "Circuit du parc de Monsanto",
                     "Florida": "Sebring International Raceway",
                     "California": "Circuit de Riverside",
                     "New York State": "Watkins Glen International",
                     "Eastern Cape Province": "Circuit Prince George",
                     "Mexico City": "Autódromo Hermanos Rodríguez",
                     "Kent": "Circuit de Brands Hatch",
                     "Styria": "Circuit de Zeltweg",
                     "Clermont-Ferrand": "Circuit de Charade",
                     "Midrand": "Circuit du Kyalami",
                     "Le Mans": "Circuit Bugatti",
                     "Ontario": "Mosport",
                     "Madrid": "Circuit permanent du Jarama",
                     "Quebec": "Circuit Mont-Tremblant",
                     "Hockenheim": "Circuit d'Hockenheim",
                     "Spielberg": "A1-Ring",
                     "Le Castellet": "Circuit Paul-Ricard",
                     "Brussels": "Circuit de Nivelles-Baulers",
                     "São Paulo": "Circuit d'Interlagos",
                     "Heusden-Zolder": "Circuit de Zolder",
                     "Anderstorp": "Circuit de Scandinavie",
                     "Dijon": "Circuit de Dijon-Prenois",
                     "Oyama": "Fuji Speedway",
                     "Rio de Janeiro": "Autódromo Internacional Nelson Piquet",
                     "Montreal": "Circuit de l'île Notre-Dame",
                     "Imola": "Autodromo Enzo e Dino Ferrari",
                     "Nevada": "Circuit urbain du Caesars Palace",
                     "Detroit": "Circuit urbain de Détroit",
                     "Dallas": "Circuit de Fair Park",
                     "Estoril": "Circuit d'Estoril",
                     "Adelaide": "Circuit urbain d'Adélaïde",
                     "Jerez de la Frontera": "Circuit permanent de Jerez",
                     "Budapest": "Hungaroring",
                     "Suzuka": "Circuit de Suzuka",
                     "Phoenix": "Circuit urbain de Phoenix",
                     "Magny Cours": "Circuit de Nevers Magny-Cours",
                     "Montmeló": "Circuit de Barcelone-Catalogne",
                     "Castle Donington": "Donington Park",
                     "Okayama": "Circuit international d'Okayama",
                     "Melbourne": "Circuit de l'Albert Park",
                     "Kuala Lumpur": "Circuit international de Sepang",
                     "Sakhir": "Circuit international de Sakhir",
                     "Shanghai": "Circuit international de Shanghai",
                     "Istanbul": "Circuit d'Istanbul Park",
                     "Valencia": "Circuit urbain de Valence",
                     "Marina Bay": "Circuit urbain de Singapour",
                     "Abu Dhabi": "Circuit Yas Marina",
                     "Yeongam County": "Circuit international de Corée",
                     "Uttar Pradesh": "Circuit international Buddh",
                     "Austin": "Circuit des Amériques",
                     "Sochi": "Autodrome de Sotchi",
                     "Baku": "Circuit urbain de Bakou",
                     "Mugello": "Circuit du Mugello",
                     "Portimão": "Circuit de Portimão",
                     "Al Daayen": "Circuit international de Losail",
                     "Jeddah": "Circuit de la corniche de Djeddah",
                     "Miami": "Autodrome international de Miami",
                     "Monaco": "Circuit de Monaco",
                     "Montréal": "Circuit Gilles-Villeneuve",
                     "Spa-Francorchamps": "Circuit de Spa-Francorchamps",
                     "Yas Island": "Circuit Yas Marina"}

CIRCUIT_WIKI_LINKS = {"Circuit de Silverstone": "https://fr.wikipedia.org/wiki/Circuit_de_Silverstone",
                      "Circuit de Monaco": "https://fr.wikipedia.org/wiki/Circuit_de_Monaco",
                      "Indianapolis Motor Speedway": "https://fr.wikipedia.org/wiki/Indianapolis_Motor_Speedway",
                      "Circuit de Bremgarten": "https://fr.wikipedia.org/wiki/Circuit_de_Bremgarten",
                      "Circuit de Spa-Francorchamps": "https://fr.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps",
                      "Circuit de Reims-Gueux": "https://fr.wikipedia.org/wiki/Circuit_de_Reims-Gueux",
                      "Autodromo nazionale di Monza": "https://fr.wikipedia.org/wiki/Autodromo_nazionale_di_Monza",
                      "Nürburgring": "https://fr.wikipedia.org/wiki/N%C3%BCrburgring",
                      "Circuit de Pedralbes": "https://fr.wikipedia.org/wiki/Circuit_de_Pedralbes",
                      "Circuit de Rouen-les-Essarts": "https://fr.wikipedia.org/wiki/Circuit_de_Rouen-les-Essarts",
                      "Circuit de Zandvoort": "https://fr.wikipedia.org/wiki/Circuit_de_Zandvoort",
                      "Autódromo de Buenos Aires": "https://fr.wikipedia.org/wiki/Aut%C3%B3dromo_Juan_y_Oscar_G%C3%A1lvez",
                      "Circuit d'Aintree": "https://fr.wikipedia.org/wiki/Circuit_d%27Aintree",
                      "Circuit de Pescara": "https://fr.wikipedia.org/wiki/Circuit_de_Pescara",
                      "Circuit de Boavista": "https://fr.wikipedia.org/wiki/Circuito_da_Boavista",
                      "Circuit d'Ain-Diab": "https://fr.wikipedia.org/wiki/Circuit_d%27Ain-Diab",
                      "AVUS": "https://fr.wikipedia.org/wiki/Automobil-Verkehrs-_und_%C3%9Cbungs-Stra%C3%9Fe_GmbH",
                      "Circuit du parc de Monsanto": "https://fr.wikipedia.org/wiki/Circuit_du_parc_de_Monsanto",
                      "Sebring International Raceway": "https://fr.wikipedia.org/wiki/Sebring_International_Raceway",
                      "Circuit de Riverside": "https://fr.wikipedia.org/wiki/Circuit_de_Riverside",
                      "Watkins Glen International": "https://fr.wikipedia.org/wiki/Watkins_Glen_International",
                      "Circuit Prince George": "https://fr.wikipedia.org/wiki/Circuit_Prince_George",
                      "Autódromo Hermanos Rodríguez": "https://fr.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez",
                      "Circuit de Brands Hatch": "https://fr.wikipedia.org/wiki/Circuit_de_Brands_Hatch",
                      "Circuit de Zeltweg": "https://fr.wikipedia.org/wiki/Circuit_de_Zeltweg",
                      "Circuit de Charade": "https://fr.wikipedia.org/wiki/Circuit_de_Charade",
                      "Circuit du Kyalami": "https://fr.wikipedia.org/wiki/Circuit_du_Kyalami",
                      "Circuit Bugatti": "https://fr.wikipedia.org/wiki/Circuit_Bugatti",
                      "Mosport": "https://fr.wikipedia.org/wiki/Canadian_Tire_Motorsport_Park",
                      "Circuit permanent du Jarama": "https://fr.wikipedia.org/wiki/Circuit_permanent_du_Jarama",
                      "Circuit Mont-Tremblant": "https://fr.wikipedia.org/wiki/Circuit_Mont-Tremblant",
                      "Circuit d'Hockenheim": "https://fr.wikipedia.org/wiki/Hockenheimring",
                      "Circuit de Spielberg": "https://fr.wikipedia.org/wiki/Circuit_de_Spielberg",
                      "Circuit Paul-Ricard": "https://fr.wikipedia.org/wiki/Circuit_Paul-Ricard",
                      "Circuit de Nivelles-Baulers": "https://fr.wikipedia.org/wiki/Circuit_de_Nivelles-Baulers",
                      "Circuit d'Interlagos": "https://fr.wikipedia.org/wiki/Autodromo_Jos%C3%A9_Carlos_Pace",
                      "Circuit de Zolder": "https://fr.wikipedia.org/wiki/Circuit_de_Zolder",
                      "Circuit de Scandinavie": "https://fr.wikipedia.org/wiki/Anderstorp_Raceway",
                      "Circuit de Dijon-Prenois": "https://fr.wikipedia.org/wiki/Circuit_de_Dijon-Prenois",
                      "Fuji Speedway": "https://fr.wikipedia.org/wiki/Fuji_Speedway",
                      "Autódromo Internacional Nelson Piquet": "https://fr.wikipedia.org/wiki/Aut%C3%B3dromo_Internacional_Nelson_Piquet",
                      "Circuit de l'île Notre-Dame": "https://fr.wikipedia.org/wiki/Circuit_Gilles-Villeneuve",
                      "Autodromo Enzo e Dino Ferrari": "https://fr.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari",
                      "Circuit urbain du Caesars Palace": "https://fr.wikipedia.org/wiki/Circuit_urbain_du_Caesars_Palace",
                      "Circuit urbain de Détroit": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_D%C3%A9troit",
                      "Circuit de Fair Park": "https://fr.wikipedia.org/wiki/Circuit_de_Fair_Park",
                      "Circuit d'Estoril": "https://fr.wikipedia.org/wiki/Circuit_d%27Estoril",
                      "Circuit urbain d'Adélaïde": "https://fr.wikipedia.org/wiki/Circuit_urbain_d%27Ad%C3%A9la%C3%AFde",
                      "Circuit permanent de Jerez": "https://fr.wikipedia.org/wiki/Circuit_permanent_de_Jerez",
                      "Hungaroring": "https://fr.wikipedia.org/wiki/Hungaroring",
                      "Circuit de Suzuka": "https://fr.wikipedia.org/wiki/Circuit_de_Suzuka",
                      "Circuit urbain de Phoenix": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_Phoenix",
                      "Circuit de Nevers Magny-Cours": "https://fr.wikipedia.org/wiki/Circuit_de_Nevers_Magny-Cours",
                      "Circuit de Barcelone-Catalogne": "https://fr.wikipedia.org/wiki/Circuit_de_Barcelone",
                      "Donington Park": "https://fr.wikipedia.org/wiki/Donington_Park",
                      "Circuit international d'Okayama": "https://fr.wikipedia.org/wiki/Circuit_international_d%27Okayama",
                      "Circuit de l'Albert Park": "https://fr.wikipedia.org/wiki/Circuit_de_l%27Albert_Park",
                      "Circuit international de Sepang": "https://fr.wikipedia.org/wiki/Circuit_international_de_Sepang",
                      "Circuit international de Sakhir": "https://fr.wikipedia.org/wiki/Circuit_international_de_Sakhir",
                      "Circuit international de Shanghai": "https://fr.wikipedia.org/wiki/Circuit_international_de_Shanghai",
                      "Circuit d'Istanbul Park": "https://fr.wikipedia.org/wiki/Otodrom_Istanbul_Park",
                      "Circuit urbain de Valence": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_Valence",
                      "Circuit urbain de Singapour": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_Singapour",
                      "Circuit Yas Marina": "https://fr.wikipedia.org/wiki/Circuit_Yas_Marina",
                      "Circuit international de Corée": "https://fr.wikipedia.org/wiki/Circuit_international_de_Cor%C3%A9e",
                      "Circuit international Buddh": "https://fr.wikipedia.org/wiki/Circuit_international_Buddh",
                      "Circuit des Amériques": "https://fr.wikipedia.org/wiki/Circuit_des_Am%C3%A9riques",
                      "Autodrome de Sotchi": "https://fr.wikipedia.org/wiki/Autodrome_de_Sotchi",
                      "Circuit urbain de Bakou": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_Bakou",
                      "Circuit du Mugello": "https://fr.wikipedia.org/wiki/Circuit_du_Mugello",
                      "Circuit de Portimão": "https://fr.wikipedia.org/wiki/Aut%C3%B3dromo_Internacional_do_Algarve",
                      "Circuit international de Losail": "https://fr.wikipedia.org/wiki/Circuit_international_de_Losail",
                      "Circuit de la corniche de Djeddah": "https://fr.wikipedia.org/wiki/Circuit_de_la_corniche_de_Djeddah",
                      "Autodrome international de Miami": "https://fr.wikipedia.org/wiki/Autodrome_international_de_Miami",
                      "Circuit de Monaco": "https://fr.wikipedia.org/wiki/Circuit_de_Monaco",
                      "Circuit Gilles-Villeneuve": "https://fr.wikipedia.org/wiki/Circuit_Gilles-Villeneuve",
                      "Circuit de Spa-Francorchamps": "https://fr.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps",
                      "Circuit Yas Marina": "https://fr.wikipedia.org/wiki/Circuit_Yas_Marina",
                      "Circuit de Montjuïc": "https://fr.wikipedia.org/wiki/Circuit_de_Montju%C3%AFc",
                      "Circuit urbain de Long Beach": "https://fr.wikipedia.org/wiki/Circuit_urbain_de_Long_Beach"}

STATUS_EN_TO_FR = {"Finished": "Fini",
                   "Disqualified": "Disqualifié",
                   "Accident": "Accident",
                   "Collision": "Collision",
                   "Engine": "Problème moteur",
                   "Gearbox": "Problème boite de vitesses",
                   "Transmission": "Problème de transmission",
                   "Clutch": "Problème d'embrayage",
                   "Hydraulics": "Problème hydraulique",
                   "Electrical": "Problème électrique",
                   "+1 Lap": "+1 Tour",
                   "+2 Laps": "+2 Tours",
                   "+3 Laps": "+3 Tours",
                   "+4 Laps": "+4 Tours",
                   "+5 Laps": "+5 Tours",
                   "+6 Laps": "+6 Tours",
                   "+7 Laps": "+7 Tours",
                   "+8 Laps": "+8 Tours",
                   "+9 Laps": "+9 Tours",
                   "Spun off": "Tête à queue",
                   "Radiator": "Problème de radiateur",
                   "Suspension": "Problème de suspension",
                   "Brakes": "Problème de freins",
                   "Differential": "Problème de différentiel",
                   "Overheating": "Surchauffe",
                   "Mechanical": "Problème mécanique",
                   "Tyre": "Problème de pneu",
                   "Driver Seat": "Problème de baquet",
                   "Puncture": "Crevaison",
                   "Driveshaft": "Problème arbre de transmission",
                   "Retired": "Abandon",
                   "Fuel pressure": "Problème de pression du carburant",
                   "Front wing": "Problème aileron avant",
                   "Water pressure": "Problème de pression hydraulique",
                   "Refuelling": "Problème ravitaillement carburant",
                   "Wheel": "Problème de volant",
                   "Throttle": "Problème de pédale d'accélération",
                   "Steering": "Problème de direction",
                   "Technical": "Problème technique",
                   "Electronics": "Problème électronique",
                   "Broken wing": "Aileron cassé",
                   "Heat shield fire": "Feu du bouclier thermique",
                   "Exhaust": "Problème de pot d'échappement",
                   "Oil leak": "Fuite d'huile",
                   "+11 Laps": "+11 Tours",
                   "Wheel rim": "Problème de jante",
                   "Water leak": "Fuite hydraulique",
                   "Fuel pump": "Problème pompe à essence",
                   "Track rod": "Problème barre de direction",
                   "+17 Laps": "+17 Tours",
                   "Oil pressure": "Problème de pression d'huile",
                   "+42 Laps": "+42 Tours",
                   "+13 Laps": "+13 Tours",
                   "Withdrew": "Forfait",
                   "+12 Laps": "+12 Tours",
                   "Engine fire": "Feu du moteur",
                   "Engine misfire": "Problème de démarrage moteur",
                   "+26 Laps": "+26 Tours",
                   "Tyre puncture": "Crevaison",
                   "Out of fuel": "Panne de carburant",
                   "Wheel nut": "Problème d'écrou de roue",
                   "Not classified": "Non classé",
                   "Pneumatics": "Problème pneumatique",
                   "Handling": "Problème de manipulation",
                   "Rear wing": "Aileron arrière",
                   "Fire": "Véhicule en feu",
                   "Wheel bearing": "Problème de roulements",
                   "Physical": "Problème de santé du pilote",
                   "Fuel system": "Problème du système de carburant",
                   "Oil line": "Problème circuit d'huile",
                   "Fuel rig": "Problème de durite d'essence",
                   "Launch control": "Collision",
                   "Injured": "Blessure",
                   "Fuel": "Problème de carburant",
                   "Power loss": "Perte de puissance moteur",
                   "Vibrations": "Vibrations",
                   "107% Rule": "Règle des 107%",
                   "Safety": "Soucis de sécurité",
                   "Drivetrain": "Problème de transmission",
                   "Ignition": "Problème de démarrage",
                   "Did not qualify": "Ne s'est pas qualifié",
                   "Injury": "Blessure",
                   "Chassis": "Problème de chassis",
                   "Battery": "Problème de batterie",
                   "Stalled": "Calage",
                   "Halfshaft": "Problème de demi-arbre de transmission",
                   "Crankshaft": "Problème de villebrequin",
                   "+10 Laps": "+10 Tours",
                   "Safety concerns": "Soucis de sécurité",
                   "Not restarted": "N'a pas redémarré",
                   "Alternator": "Problème d'alternateur",
                   "Underweight": "Problème de poids de la voiture",
                   "Safety belt": "Problème de ceinture de sécurité",
                   "Oil pump": "Problème de pompe à huile",
                   "Fuel leak": "Fuite de carburant",
                   "Excluded": "Exclusion",
                   "Did not prequalify": "Ne s'est pas pré-qualifié",
                   "Injection": "Problème d'injecteurs",
                   "Distributor": "Problème de distributeur",
                   "Driver unwell": "Mauvaise santé du pilote",
                   "Turbo": "Problème de turbo",
                   "CV joint": "Problème de transmission",
                   "Water pump": "Problème de pompe hydraulique",
                   "Fatal accident": "Accident mortel",
                   "Spark plugs": "Problème de bougies",
                   "Fuel pipe": "Problème du circuit de carburant",
                   "Eye injury": "Blessure à l'oeil",
                   "Oil pipe": "Problème du circuit d'huile",
                   "Axle": "Problème d'essieu",
                   "Water pipe": "Problème du circuit hydraulique",
                   "+14 Laps": "+14 Tours",
                   "+15 Laps": "+15 Tours",
                   "+25 Laps": "+25 Tours",
                   "+18 Laps": "+18 Tours",
                   "+22 Laps": "+22 Tours",
                   "+16 Laps": "+16 Tours",
                   "+24 Laps": "+24 Tours",
                   "+29 Laps": "+29 Tours",
                   "+23 Laps": "+23 Tours",
                   "+21 Laps": "+21 Tours",
                   "Magneto": "Problème de magnéto d'allumage",
                   "+44 Laps": "+44 Tours",
                   "+30 Laps": "+30 Tours",
                   "+19 Laps": "+19 Tours",
                   "+46 Laps": "+46 Tours",
                   "Supercharger": "Problème de compresseur",
                   "+20 Laps": "+20 Tours",
                   "Collision damage": "Dommages suite à une collision",
                   "Power Unit": "Problème d'unité de puissance",
                   "ERS": "Problème d'ERS",
                   "+49 Laps": "+49 Tours",
                   "+38 Laps": "+38 Tours",
                   "Brake duct": "Problème d'écope de frein",
                   "Seat": "Abandon",
                   "Damage": "Dommages sur la voiture",
                   "Debris": "Débris",
                   "Illness": "Maladie",
                   "Undertray": "Problème de fond plat",
                   "Cooling system": "Problème du système de refroidissement",
                   "": "a déterminer"}

SESSION_NAMES_EN_TO_FR = {"Qualifying": "Qualifications",
                          "Race": "Course",
                          "Sprint Qualifying": "Qualifications Sprint",
                          "Sprint": "Qualifications Sprint"}

NATIONALITY_EN_TO_FR = {"British": "Britannique",
                        "German": "Allemand",
                        "Spanish": "Espagnol",
                        "Finnish": "Finlandais",
                        "Japanese": "Japonais",
                        "French": "Français",
                        "Polish": "Polonais",
                        "Brazilian": "Brésilien",
                        "Italian": "Italien",
                        "Australian": "Australien",
                        "Austrian": "Autrichien",
                        "American": "Américain",
                        "Dutch": "Néerlandais",
                        "Colombian": "Colombien",
                        "Portuguese": "Portugais",
                        "Canadian": "Canadien",
                        "Indian": "Indien",
                        "Hungarian": "Hongrois",
                        "Irish": "Irlandais",
                        "Danish": "Danois",
                        "Argentine": "Argentin",
                        "Czech": "Tchèque",
                        "Malaysian": "Malaisien",
                        "Swiss": "Suisse",
                        "Belgian": "Belge",
                        "Monegasque": "Monégasque",
                        "Swedish": "Suédois",
                        "Venezuelan": "Vénézuélien",
                        "New Zealander": "Néo-zélandais",
                        "Chilean": "Chilien",
                        "Mexican": "Mexicain",
                        "South African": "Sud-africain",
                        "Liechtensteiner":"Liechtensteinois",
                        "Rhodesian": "Rhodésien",
                        "American-Italian": "Américain",
                        "Uruguayan": "Uruguayen",
                        "Argentine-Italian": "Argentin",
                        "Thai": "Thaïlandais",
                        "East German": "Allemand",
                        "Russian": "Russe",
                        "Indonesian": "Indonésien",
                        "Chinese": "Chinois"
                        }
